--
-- Data Model for Content Repository
--

CREATE TABLE ${prefix}CONTENTFILE
(
    FILE_NAME VARCHAR2(128) NOT NULL,
    EXT_FILE_ID VARCHAR2(128),
    PERMISSION_OBJECT_TYPE VARCHAR2(128) NOT NULL,
    FOLDER_ID NUMBER(*) NOT NULL,
    STATUS_SCHEMA_ID VARCHAR2(128) NOT NULL,
    FILE_ID NUMBER(*) PRIMARY KEY NOT NULL,
    SECURITY_SCHEMA_ID VARCHAR2(128) NOT NULL,
    STATUS_ID VARCHAR2(128) NOT NULL,
    PERMISSION_OBJECT_ID VARCHAR2(128) NOT NULL
);

CREATE TABLE ${prefix}CONTENTFOLDER
(
    FOLDER_DESCRIPTION VARCHAR2(128) NOT NULL,
    PERMISSION_OBJECT_TYPE VARCHAR2(128) NOT NULL,
    STATUS_SCHEMA_ID VARCHAR2(128) NOT NULL,
    FOLDER_NAME VARCHAR2(128) NOT NULL,
    FOLDER_ID NUMBER(*) PRIMARY KEY NOT NULL,
    SECURITY_SCHEMA_ID VARCHAR2(128) NOT NULL,
    STATUS_ID VARCHAR2(128) NOT NULL,
    CONTENT_ID NUMBER(*) NOT NULL,
    PERMISSION_OBJECT_ID VARCHAR2(128) NOT NULL,
    PARENT_FOLDER NUMBER(*),
    CURRENT_STATUS VARCHAR2(128) NOT NULL
);

CREATE TABLE ${prefix}CONTENTREPOSITORY
(
    NAME VARCHAR2(128) NOT NULL,
    PERMISSION_OBJECT_TYPE VARCHAR2(128) NOT NULL,
    PROVIDER VARCHAR2(128) NOT NULL,
    CONTENT_ID NUMBER(*) PRIMARY KEY NOT NULL,
    PERMISSION_OBJECT_ID VARCHAR2(128) NOT NULL
);

CREATE TABLE ${prefix}CONTENTREPOSITORYCONFIG
(
    CONFIGKEY VARCHAR2(128) NOT NULL,
    CONTENT_CONFIGUATION_ID NUMBER(*) PRIMARY KEY NOT NULL,
    CONTENT_ID NUMBER(*) NOT NULL,
    VALUE VARCHAR2(128) NOT NULL
);

CREATE TABLE ${prefix}MIMEMAPPING
(
    MIME_TYPE VARCHAR2(128) NOT NULL,
    MIME_MAPPING_ID NUMBER(*) PRIMARY KEY NOT NULL,
    EXT VARCHAR2(128) NOT NULL
);

ALTER TABLE ${prefix}CONTENTFILE ADD FOREIGN KEY (FOLDER_ID) REFERENCES ${prefix}CONTENTFOLDER (FOLDER_ID);
ALTER TABLE ${prefix}CONTENTFOLDER ADD FOREIGN KEY (CONTENT_ID) REFERENCES ${prefix}CONTENTREPOSITORY (CONTENT_ID);
ALTER TABLE ${prefix}CONTENTFOLDER ADD FOREIGN KEY (PARENT_FOLDER) REFERENCES ${prefix}CONTENTFOLDER (FOLDER_ID);
ALTER TABLE ${prefix}CONTENTREPOSITORYCONFIG ADD FOREIGN KEY (CONTENT_ID) REFERENCES ${prefix}CONTENTREPOSITORY (CONTENT_ID);
CREATE UNIQUE INDEX ${prefix}IDX2DDB05D3 ON ${prefix}MIMEMAPPING (EXT);

CREATE SEQUENCE ${prefix}S_REPO  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE ${prefix}S_REPOCONFIG  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE ${prefix}S_CFOLDER  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE ${prefix}S_CFILE  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
CREATE SEQUENCE ${prefix}S_MIME  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

