ALTER TABLE ${prefix}CONTENTFILE
    ADD REC_DATE DATE DEFAULT NULL;
ALTER TABLE ${prefix}CONTENTFILE
    ADD REC_USER VARCHAR2(128) DEFAULT NULL;
ALTER TABLE ${prefix}CONTENTFILE
    ADD CHG_DATE DATE DEFAULT NULL;
ALTER TABLE ${prefix}CONTENTFILE
    ADD CHG_USER VARCHAR2(128) DEFAULT NULL;